### ISSUE TITLE
Open Error! Try again!

### ISSUE THREAD

**Issue by qiqingwang577** [bubbliiiing/mask-rcnn-keras#10]
请问，执行预测的时候，我在"Input image filename:"的后面输入street，为什么提示我"Open Error! Try again!"呢?我该如何键入想要预测的图片?

**Comment by qiqingwang577** [comment]
> 请问，执行预测的时候，我在"Input image filename:"的后面输入street，为什么提示我"Open Error! Try again!"呢?我该如何键入想要预测的图片?

看了作者的b站，我弄懂了！很小的问题，作者在b站里讲的很清楚！

PS:
我是先搜索到作者的github，然后顺着找到了作者在csdn里发的博客，然后从博客下面的评论里知道作者有b站，再去b站看的。还好作者在github，csdn，b站上都用的同一个名字。感觉像我这个顺序的人应该不多。。。我说怎么在Issues里提问的人很少，大家去看b站的，看完基本上就没问题了！

**Comment by iiiicode** [comment]
B站账号找不到啊，可以加个QQ吗2815839406

**Comment by iiiicode** [comment]
> > 请问，执行预测的时候，我在"Input image filename:"的后面输入street，为什么提示我"Open Error! Try again!"呢?我该如何键入想要预测的图片?
> 
> 看了作者的b站，我弄懂了！很小的问题，作者在b站里讲的很清楚！
> 
> PS:
> 我是先搜索到作者的github，然后顺着找到了作者在csdn里发的博客，然后从博客下面的评论里知道作者有b站，再去b站看的。还好作者在github，csdn，b站上都用的同一个名字。感觉像我这个顺序的人应该不多。。。我说怎么在Issues里提问的人很少，大家去看b站的，看完基本上就没问题了！

**Comment by iiiicode** [comment]
B站账号找不到啊，可以加个QQ吗2815839406
