### ISSUE TITLE
ValueError: Error when checking input: expected input_image_meta to have shape (13,) but got array with shape (16,)

### ISSUE THREAD

**Issue by qiqingwang577** [bubbliiiing/mask-rcnn-keras#11]
我正在训练1类物体，按照up主说的，一步一步都准备好了，但是在训练的时候报错: ValueError: Error when checking input: expected input_image_meta to have shape (14,) but got array with shape (16,) 请问该怎么解决? 提前谢谢了！
我的NUM_CLASSES = 1 + 1

**Comment by qiqingwang577** [comment]
> 我正在训练1类物体，按照up主说的，一步一步都准备好了，但是在训练的时候报错: ValueError: Error when checking input: expected input_image_meta to have shape (14,) but got array with shape (16,) 请问该怎么解决? 提前谢谢了！
> 我的NUM_CLASSES = 1 + 1

我已经解决了，提醒大家再次检车NUM_CLASSES，我出现这个问题是，虽然我的NUM_CLASSES没错，但是我train时路径不对，导入的dataset是旧文件。。。

**Comment by bubbliiiing** [comment]
好的加油！
