### ISSUE TITLE
关于标注样本的提问

### ISSUE THREAD

**Issue by FortuneStar** [bubbliiiing/mask-rcnn-keras#3]
您在“准备数据集”中写道“利用labelme标注数据集，注意标注的时候同一个类要用不同的序号，比如画面中存在两个苹果那么一个苹果的label就是apple1另一个是apple2。”如果按照这种方式标记，那么运行json_to_dataset.py后的yaml文中也会带有编号，但是我看您上传的正方形、三角形圆形的例子中的yaml没有编号，即使一张图片有相同的图形。

**Comment by bubbliiiing** [comment]
例子是用程序生成的，所以没有
