### ISSUE TITLE
使用resnet50训练

### ISSUE THREAD

**Issue by theoning** [bubbliiiing/mask-rcnn-keras#38]
请问如果想用resnet50结构作为backbone，是不是只需要修改resnet.py里的block count，resnet101的block count是22，resnet50是5
![image](https://user-images.githubusercontent.com/79895774/177026228-602c5a8d-a221-47bd-98e7-478543028844.png)

**Comment by bubbliiiing** [comment]
理论上是可以

**Comment by theoning** [comment]
> 理论上是可以

好滴，谢谢
