### ISSUE TITLE
请问这个报错怎么办，是我版本不对吗? ValueError: Cannot iterate over a shape with unknown rank.

### ISSUE THREAD

**Issue by qiqingwang577** [bubbliiiing/mask-rcnn-keras#8]
我用的版本:
tensorflow==1.14.0
keras==2.3.1
没有gpu
提前谢谢了！

**Comment by bubbliiiing** [comment]
换个版本吧老铁

**Comment by qiqingwang577** [comment]
> 换个版本吧老铁

请问python需要什么版本?

**Comment by bubbliiiing** [comment]
tf和keras，按readme配置

**Comment by qiqingwang577** [comment]
> tf和keras，按readme配置感谢你回复！现在有个别的问题, 运行预测的时候，我在"Input image filename:"后面输入street，为什么显示Open Error! Try again! 呢?

**Comment by qiqingwang577** [comment]
> tf和keras，按readme配置

感谢你的回复，我配置好了！但是现在有个别的问题，执行预测的时候我在"Input image filename:"的后面输入street，为什么提示我"Open Error! Try again!"呢?我该如何键入想要预测的图片?

**Comment by qiqingwang577** [comment]
> tf和keras，按readme配置

感谢你的回复，我配置好了！
